services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                NEXT_PUBLIC_API_BASE_URL: https://api.fillando.com
        container_name: fillando-fe
        restart: unless-stopped
        env_file: .env.prod
        ports:
            - '3000:3000'
