/**
 * Delivery estimate from the variant's shipping weight (TD-0006 §5.4).
 *
 * Nova Poshta sells "Стандарт" warehouse-to-warehouse in weight steps, not per kilogram, and
 * prices a parcel differently inside one city and across the country. So the table has two
 * tiers × two zones. The storefront cannot know the shopper's city on a product page, so it
 * quotes the country-wide zone — the conservative figure — and Merchant Center's account-level
 * shipping is configured from the same numbers.
 *
 * The numbers are generated by `fillando-be/scripts/shipping-rates.js` from the shop's real
 * Nova Poshta contract (`InternetDocument.getDocumentPrice`). Do not edit them by hand: rerun
 * the script and paste its output here.
 */
export const SHIPPING_RATE_TABLE = {
	/** Date the numbers were pulled by `shipping-rates.js` (fillando-be, scripts/shipping-rates.json). */
	generated_at: '2026-09-06' as string | null,
	source: 'nova-post-api' as 'placeholder' | 'nova-post-api',
	/** Declared value the quote was requested with — the insurance fee depends on it. */
	declared_value_uah: 600,
	/** Львів → Львів («по місту») and Львів → Київ («по Україні»), Стандарт, відділення–відділення. */
	tiers: [
		{ max_weight_g: 2000, city_uah: 73, ukraine_uah: 93 },
		{ max_weight_g: 10000, city_uah: 118, ukraine_uah: 138 }
	]
} as const

export type ShippingZone = 'city' | 'ukraine'

export type ShippingTransitDays = { min: number; max: number }

/** A parcel the table prices — the only state that carries a ₴ figure. */
export type ShippingQuote = {
	kind: 'quoted'
	rate_uah: number
	zone: ShippingZone
	/** Upper bound of the tier the parcel fell into, grams. */
	max_weight_g: number
	transit_days: ShippingTransitDays
}

/** No usable weight on the variant, so nothing about the parcel can be said honestly. */
export type ShippingWeightUnknown = {
	kind: 'weight_unknown'
	transit_days: ShippingTransitDays
}

/** The weight is known — the contract table simply stops below it. */
export type ShippingAboveTable = {
	kind: 'above_table'
	/** Top step of the table the parcel is heavier than, grams. */
	over_weight_g: number
	transit_days: ShippingTransitDays
}

export type ShippingEstimate = ShippingQuote | ShippingWeightUnknown | ShippingAboveTable

const TRANSIT_DAYS = { min: 1, max: 3 } as const

/** Heaviest parcel the contract table prices, grams. */
const TOP_WEIGHT_G = Math.max(...SHIPPING_RATE_TABLE.tiers.map(t => t.max_weight_g))

/**
 * Which of three states the variant's shipping weight puts the page in.
 *
 * Three, because two of them used to share one `null` and every caller read that as «no weight»:
 * a stored 0 g quoted the cheapest tier as if it had been measured, and a parcel over the top
 * step told the shopper the weight was not specified while it was (Plan-0005 I-14). Only
 * `kind: 'quoted'` may be turned into a number — the other two are the signal to say so, never
 * to show a default figure.
 */
export const estimateShipping = (
	weightG: number | null | undefined,
	zone: ShippingZone = 'ukraine'
): ShippingEstimate => {
	// A non-positive weight is data, not a parcel: 0 is what an unfilled field backfills to.
	if (weightG === null || weightG === undefined || !Number.isFinite(weightG) || weightG <= 0) {
		return { kind: 'weight_unknown', transit_days: TRANSIT_DAYS }
	}
	const tier = SHIPPING_RATE_TABLE.tiers.find(t => weightG <= t.max_weight_g)
	if (!tier) {
		return { kind: 'above_table', over_weight_g: TOP_WEIGHT_G, transit_days: TRANSIT_DAYS }
	}
	return {
		kind: 'quoted',
		rate_uah: zone === 'city' ? tier.city_uah : tier.ukraine_uah,
		zone,
		max_weight_g: tier.max_weight_g,
		transit_days: TRANSIT_DAYS
	}
}

/** schema.org OfferShippingDetails, or undefined unless the table actually prices the parcel. */
export const buildShippingDetails = (weightG: number | null | undefined) => {
	const estimate = estimateShipping(weightG)
	if (estimate.kind !== 'quoted') return undefined
	return {
		'@type': 'OfferShippingDetails',
		shippingRate: {
			'@type': 'MonetaryAmount',
			value: estimate.rate_uah,
			currency: 'UAH'
		},
		shippingDestination: {
			'@type': 'DefinedRegion',
			addressCountry: 'UA'
		},
		deliveryTime: {
			'@type': 'ShippingDeliveryTime',
			handlingTime: {
				'@type': 'QuantitativeValue',
				minValue: 0,
				maxValue: 1,
				unitCode: 'DAY'
			},
			transitTime: {
				'@type': 'QuantitativeValue',
				minValue: estimate.transit_days.min,
				maxValue: estimate.transit_days.max,
				unitCode: 'DAY'
			}
		}
	}
}
