/**
 * Delivery estimate from the variant's shipping weight (TD-0006 §5.4).
 *
 * Nova Poshta sells "Стандарт" warehouse-to-warehouse in weight steps, not per kilogram, and
 * prices a parcel differently inside one city and across the country. So the table has two
 * tiers × two zones. The storefront cannot know the shopper's city on a product page, so it
 * quotes the country-wide zone — the conservative figure — and Merchant Center's account-level
 * shipping is configured from the same numbers.
 *
 * The numbers are generated by `fillando-be/scripts/shipping-rates.js` from the shop's real
 * Nova Poshta contract (`InternetDocument.getDocumentPrice`). Do not edit them by hand: rerun
 * the script and paste its output here.
 */
export const SHIPPING_RATE_TABLE = {
	/** ISO date the numbers were pulled; null while the table is still a placeholder. */
	generated_at: null as string | null,
	source: 'placeholder' as 'placeholder' | 'nova-post-api',
	/** Declared value the quote was requested with — the insurance fee depends on it. */
	declared_value_uah: 600,
	tiers: [
		{ max_weight_g: 2000, city_uah: 97, ukraine_uah: 97 },
		{ max_weight_g: 10000, city_uah: 97, ukraine_uah: 97 }
	]
} as const

export type ShippingZone = 'city' | 'ukraine'

export type ShippingEstimate = {
	rate_uah: number
	zone: ShippingZone
	/** Upper bound of the tier the parcel fell into, grams. */
	max_weight_g: number
	transit_days: { min: number; max: number }
}

const TRANSIT_DAYS = { min: 1, max: 3 } as const

/**
 * The tier a parcel of `weightG` grams falls into, or null when there is no weight or it is
 * heavier than the table covers. Null is the signal to omit the estimate entirely — never to
 * show a default number.
 */
export const estimateShipping = (
	weightG: number | null | undefined,
	zone: ShippingZone = 'ukraine'
): ShippingEstimate | null => {
	if (weightG === null || weightG === undefined || !Number.isFinite(weightG) || weightG < 0) {
		return null
	}
	const tier = SHIPPING_RATE_TABLE.tiers.find(t => weightG <= t.max_weight_g)
	if (!tier) return null
	return {
		rate_uah: zone === 'city' ? tier.city_uah : tier.ukraine_uah,
		zone,
		max_weight_g: tier.max_weight_g,
		transit_days: TRANSIT_DAYS
	}
}

/** schema.org OfferShippingDetails for the estimate, or undefined when there is none. */
export const buildShippingDetails = (weightG: number | null | undefined) => {
	const estimate = estimateShipping(weightG)
	if (!estimate) return undefined
	return {
		'@type': 'OfferShippingDetails',
		shippingRate: {
			'@type': 'MonetaryAmount',
			value: estimate.rate_uah,
			currency: 'UAH'
		},
		shippingDestination: {
			'@type': 'DefinedRegion',
			addressCountry: 'UA'
		},
		deliveryTime: {
			'@type': 'ShippingDeliveryTime',
			handlingTime: {
				'@type': 'QuantitativeValue',
				minValue: 0,
				maxValue: 1,
				unitCode: 'DAY'
			},
			transitTime: {
				'@type': 'QuantitativeValue',
				minValue: estimate.transit_days.min,
				maxValue: estimate.transit_days.max,
				unitCode: 'DAY'
			}
		}
	}
}
